from sqlalchemy.orm import Session
from datetime import datetime
import models, schemas, auth, os, tempfile

def get_user_by_email(db, email):
    return db.query(models.User).filter(models.User.email == email).first()

def create_user(db, user: schemas.UserCreate):
    # First user becomes admin
    is_admin = db.query(models.User).count() == 0
    db_user = models.User(
        username=user.username,
        email=user.email,
        password=auth.hash_password(user.password),
        is_admin=is_admin
    )
    db.add(db_user)
    db.commit()
    db.refresh(db_user)
    return db_user

def get_all_users(db):
    return db.query(models.User).order_by(models.User.created_at.desc()).all()

def toggle_ban(db, user_id: int):
    user = db.query(models.User).filter(models.User.id == user_id).first()
    if user:
        user.is_banned = not user.is_banned
        db.commit()
    return {"banned": user.is_banned}

def create_scan(db, payload: schemas.ScanCreate, user_id: int):
    scan = models.Scan(user_id=user_id, target_url=payload.target_url)
    db.add(scan)
    db.commit()
    db.refresh(scan)
    return scan

def get_scan(db, scan_id: int):
    return db.query(models.Scan).filter(models.Scan.id == scan_id).first()

def get_scans_by_user(db, user_id: int):
    return db.query(models.Scan).filter(
        models.Scan.user_id == user_id
    ).order_by(models.Scan.created_at.desc()).all()

def get_all_scans(db):
    return db.query(models.Scan).order_by(models.Scan.created_at.desc()).all()

def delete_scan(db, scan_id: int):
    scan = db.query(models.Scan).filter(models.Scan.id == scan_id).first()
    if scan:
        db.delete(scan)
        db.commit()

SEV_ICONS = {"ok": "✅", "warning": "⚠️", "critical": "❌", "info": "ℹ️"}

def generate_report(scan: models.Scan) -> str:
    lines = []
    lines.append("=" * 70)
    lines.append("  mr7.ai — Security Scan Report")
    lines.append("=" * 70)
    lines.append(f"  Target   : {scan.target_url}")
    lines.append(f"  Date     : {scan.created_at.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"  Status   : {scan.status.upper()}")
    lines.append(f"  Risk Score: {scan.risk_score}/100")
    lines.append("=" * 70)
    lines.append("")

    if scan.results:
        current_cat = None
        for r in scan.results:
            cat = r.get("category", "")
            if cat != current_cat:
                if current_cat is not None:
                    lines.append("│")
                lines.append(f"├── [{cat}]")
                current_cat = cat
            icon = SEV_ICONS.get(r.get("severity", "info"), "•")
            check = r.get("check", "")
            detail = r.get("detail", "")
            status = r.get("status", "")
            lines.append(f"│   ├── {icon} {check}")
            lines.append(f"│   │       {status}: {detail}")
        lines.append("│")
        lines.append("└── End of Report")

    lines.append("")
    lines.append("=" * 70)
    lines.append("  Generated by mr7.ai — Authorized Security Research Platform")
    lines.append("=" * 70)

    content = "\n".join(lines)
    path = os.path.join(tempfile.gettempdir(), f"mr7_report_{scan.id}.txt")
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return path
